FROM node:16.18 as dependencies
WORKDIR /app
COPY package.json ./

RUN npm install

FROM node:16.18 as builder
WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules

RUN npx prisma generate

FROM node:16.18 as runner
WORKDIR /app

COPY --from=builder /app/ .