version: '3'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -p ${POSTGRES_PORT} -U postgres
      interval: 10s
      timeout: 5s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    command: bash -c "npm run prisma migrate deploy && npm run prisma db seed && npm run start"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
  server:
    build: ./nginx
    depends_on:
      - app
    ports:
      - 80:80

volumes:
  postgres:
