version: '3'
services:
  postgres-test-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: postgres -p ${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -p ${POSTGRES_PORT} -U postgres
      interval: 10s
      timeout: 5s
      retries: 10

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: app
    depends_on:
      postgres-test-db:
        condition: service_healthy
    working_dir: /app
    command: bash -c "npm run prisma migrate deploy && npm run prisma db seed && npm run test"
    environment:
      NODE_ENV: test
      DATABASE_URL: ${DATABASE_URL}
